name: Generate Hashes JSON

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-hashes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate hashes.json
        run: |
          OUTPUT_FILE="hashes.json"
          HASHES_JSON="[]"

          json_escape() {
            printf '%s' "$1" | sed 's|\\|\\\\|g; s|"|\\"|g; s|\n|\\n|g; s|\r|\\r|g; s|\t|\\t|g'
          }

          find . -type f \
            ! -path './.git/*' \
            ! -path "./$OUTPUT_FILE" \
            | sort | while read file; do

            rel_path="${file#./}"
            filename="$(basename "$file")"
            sha256=$(sha256sum "$file" | awk '{print $1}')

            entry="{
              \"Name\": \"$(json_escape "$filename")\",
              \"SHA256\": \"$sha256\",
              \"RelativePath\": \"$(json_escape "$rel_path")\"
            }"

            HASHES_JSON=$(echo "$HASHES_JSON" | jq --argjson item "$entry" '. += [$item]')
          done

          echo "$HASHES_JSON" | jq '.' > "$OUTPUT_FILE"
          echo "✅ Generated $OUTPUT_FILE with $(jq '. | length' "$OUTPUT_FILE") file(s)."

      - name: Display hashes.json
        run: cat hashes.json

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update hashes.json for tag ${{ github.ref_name }}"
          file_pattern: hashes.json
          branch: ${{ github.head_ref || github.ref_name }}