name: Generate Hashes JSON

on:
  push:
    tags:
      - '*'  # 推送任意 tag 触发
  workflow_dispatch:  # 手动触发

permissions:
  contents: write  # 允许提交更改

jobs:
  generate-hashes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (if needed)
        run: |
          # 如果你需要额外库（如 rich），可以 pip install
          # pip install rich
          echo "No extra dependencies."

      - name: Run generate-hashes.py
        run: python .scripts/generate-hashes.py

      - name: Show hashes.json
        run: cat hashes.json

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update hashes.json for tag ${{ github.ref_name }}"
          file_pattern: hashes.json
          branch: ${{ github.ref_name }}